In [3]:
import urllib.request as url

In [4]:
import urllib.request
import json 
url = urllib.request.urlopen('http://ctabustracker.com/bustime/eta/eta.jsp?route=---&direction=---&stop=---&id=162&showAllBusses=on&findstop=on')
covid = urllib.request.urlopen('https://covidtracking.com/api/v1/states/daily.json')
covid_data = covid.read()
COVID_JSON = json.loads(covid_data)
print(COVID_JSON)

Help on list object:

class list(object)
 |  list(iterable=(), /)
 |
 |  Built-in mutable sequence.
 |
 |  If no argument is given, the constructor creates a new empty list.
 |  The argument must be an iterable if specified.
 |
 |  Methods defined here:
 |
 |  __add__(self, value, /)
 |      Return self+value.
 |
 |  __contains__(self, key, /)
 |      Return key in self.
 |
 |  __delitem__(self, key, /)
 |      Delete self[key].
 |
 |  __eq__(self, value, /)
 |      Return self==value.
 |
 |  __ge__(self, value, /)
 |      Return self>=value.
 |
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |
 |  __getitem__(...)
 |      x.__getitem__(y) <==> x[y]
 |
 |  __gt__(self, value, /)
 |      Return self>value.
 |
 |  __iadd__(self, value, /)
 |      Implement self+=value.
 |
 |  __imul__(self, value, /)
 |      Implement self*=value.
 |
 |  __init__(self, /, *args, **kwargs)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |
 |  __iter__(self, /)
 |      Implement iter(self).
 |
 |  __le__(self, value, /)
 |      Return self<=value.
 |
 |  __len__(self, /)
 |      Return len(self).
 |
 |  __lt__(self, value, /)
 |      Return self<value.
 |
 |  __mul__(self, value, /)
 |      Return self*value.
 |
 |  __ne__(self, value, /)
 |      Return self!=value.
 |
 |  __repr__(self, /)
 |      Return repr(self).
 |
 |  __reversed__(self, /)
 |      Return a reverse iterator over the list.
 |
 |  __rmul__(self, value, /)
 |      Return value*self.
 |
 |  __setitem__(self, key, value, /)
 |      Set self[key] to value.
 |
 |  __sizeof__(self, /)
 |      Return the size of the list in memory, in bytes.
 |
 |  append(self, object, /)
 |      Append object to the end of the list.
 |
 |  clear(self, /)
 |      Remove all items from list.
 |
 |  copy(self, /)
 |      Return a shallow copy of the list.
 |
 |  count(self, value, /)
 |      Return number of occurrences of value.
 |
 |  extend(self, iterable, /)
 |      Extend list by appending elements from the iterable.
 |
 |  index(self, value, start=0, stop=9223372036854775807, /)
 |      Return first index of value.
 |
 |      Raises ValueError if the value is not present.
 |
 |  insert(self, index, object, /)
 |      Insert object before index.
 |
 |  pop(self, index=-1, /)
 |      Remove and return item at index (default last).
 |
 |      Raises IndexError if list is empty or index is out of range.
 |
 |  remove(self, value, /)
 |      Remove first occurrence of value.
 |
 |      Raises ValueError if the value is not present.
 |
 |  reverse(self, /)
 |      Reverse *IN PLACE*.
 |
 |  sort(self, /, *, key=None, reverse=False)
 |      Stable sort *IN PLACE*.
 |
 |  ----------------------------------------------------------------------
 |  Static methods defined here:
 |
 |  __new__(*args, **kwargs) from builtins.type
 |      Create and return a new object.  See help(type) for accurate signature.
 |
 |  ----------------------------------------------------------------------
 |  Data and other attributes defined here:
 |
 |  __hash__ = None

None

In [5]:
from pandas import DataFrame as DF

In [6]:
url = urllib.request.urlopen('https://covidtracking.com/api/v1/states/current.json')
data = url.read()
parse_json = json.loads(data)
pdf = DF(parse_json)

In [7]:
pdf.columns

Index(['state', 'positive', 'positiveScore', 'negativeScore',
       'negativeRegularScore', 'commercialScore', 'grade', 'score', 'notes',
       'dataQualityGrade', 'negative', 'pending', 'hospitalizedCurrently',
       'hospitalizedCumulative', 'inIcuCurrently', 'inIcuCumulative',
       'onVentilatorCurrently', 'onVentilatorCumulative', 'recovered',
       'lastUpdateEt', 'checkTimeEt', 'death', 'hospitalized', 'total',
       'totalTestResults', 'posNeg', 'fips', 'dateModified', 'dateChecked',
       'hash'],
      dtype='object')

In [14]:
import numpy as np

In [15]:
pdf

,state,positive,positiveScore,negativeScore,negativeRegularScore,commercialScore,grade,score,notes,dataQualityGrade,...,checkTimeEt,death,hospitalized,total,totalTestResults,posNeg,fips,dateModified,dateChecked,hash
0,AK,339,1.0,1.0,1.0,1.0,A,4.0,"Please stop using the ""total"" field. Use ""tota...",B,...,4/24 16:02,9.0,NaN,12281,12281,12281,02,2020-04-24T19:00:00Z,2020-04-24T20:02:00Z,829ac690ed4c16079a6f1890fcf8105935a055ff
1,AL,5832,1.0,1.0,0.0,1.0,B,3.0,"Please stop using the ""total"" field. Use ""tota...",B,...,4/24 16:05,197.0,768.0,52695,52695,52695,01,2020-04-24T04:00:00Z,2020-04-24T20:05:00Z,45ada0943397a4f5bd08772ab110f0594bbc7e02
2,AR,2741,1.0,1.0,1.0,1.0,A,4.0,"Please stop using the ""total"" field. Use ""tota...",B,...,4/24 15:42,45.0,291.0,35578,35578,35578,05,2020-04-24T14:47:00Z,2020-04-24T19:42:00Z,e70e363b75b64ad74efd0b6d046672c6e818750b
3,AZ,6045,1.0,1.0,0.0,1.0,B,3.0,"Please stop using the ""total"" field. Use ""tota...",A+,...,4/24 15:39,266.0,984.0,60714,60714,60714,04,2020-04-24T04:00:00Z,2020-04-24T19:39:00Z,72d72c4092636c2a96a366a5895055feccc0aeef
4,CA,39254,1.0,1.0,0.0,1.0,B,3.0,"Please stop using the ""total"" field. Use ""tota...",B,...,4/24 17:00,1562.0,NaN,494173,494173,494173,06,2020-04-23T04:00:00Z,2020-04-24T21:00:00Z,0711cfd3633ed6d50a0d5f33573f8929f3dfaed2
5,CO,11262,1.0,1.0,1.0,1.0,A,4.0,"Please stop using the ""total"" field. Use ""tota...",C,...,4/24 15:52,552.0,2237.0,52324,52324,52324,08,2020-04-23T04:00:00Z,2020-04-24T19:52:00Z,80390462b00d2eb665810b44b4eebe90c50be35f
6,CT,23921,1.0,1.0,1.0,1.0,A,4.0,"Please stop using the ""total"" field. Use ""tota...",C,...,4/24 17:03,1764.0,NaN,74038,74038,74038,09,2020-04-24T20:00:00Z,2020-04-24T21:03:00Z,7d8a5fbd78b7fa19f6e713f22383c9dca80f57bf
7,DC,3528,1.0,1.0,1.0,1.0,A,4.0,"Please stop using the ""total"" field. Use ""tota...",A+,...,4/24 16:11,153.0,NaN,16533,16533,16533,11,2020-04-23T04:00:00Z,2020-04-24T20:11:00Z,b201fd045daf11cb21270054ea3737ae58c477dd
8,DE,3442,1.0,1.0,1.0,1.0,A,4.0,"Please stop using the ""total"" field. Use ""tota...",C,...,4/24 16:16,100.0,NaN,17379,17379,17379,10,2020-04-23T22:00:00Z,2020-04-24T20:16:00Z,e31ad6975732e8bf659a2bed46637352717e95be
9,FL,30174,1.0,1.0,1.0,1.0,A,4.0,"Please stop using the ""total"" field. Use ""tota...",C,...,4/24 16:23,1031.0,4888.0,318246,316959,316959,12,2020-04-24T13:41:00Z,2020-04-24T20:23:00Z,839baf0394d82f4a72040ed93679d35b0ea391ea
10,GA,22147,1.0,1.0,1.0,1.0,A,4.0,"Please stop using the ""total"" field. Use ""tota...",B,...,4/24 16:26,892.0,4221.0,107176,107176,107176,13,2020-04-24T15:28:00Z,2020-04-24T20:26:00Z,44f24ebc70052d04096a3ecf7a7b3361ec895955
11,HI,596,1.0,1.0,1.0,1.0,A,4.0,"Please stop using the ""total"" field. Use ""tota...",D,...,4/24 15:40,12.0,63.0,26887,26887,26887,15,2020-04-23T22:00:00Z,2020-04-24T19:40:00Z,4054a6bc0decc1a1ae7c6a9db191f28733c1d24e
12,IA,4445,1.0,1.0,1.0,1.0,A,4.0,"Please stop using the ""total"" field. Use ""tota...",B,...,4/24 15:03,107.0,NaN,31973,31973,31973,19,2020-04-23T16:00:00Z,2020-04-24T19:03:00Z,a6033303518fbb5a992ba4f813170fab77b90525
13,ID,1836,1.0,1.0,1.0,1.0,A,4.0,"Please stop using the ""total"" field. Use ""tota...",C,...,4/24 16:34,54.0,166.0,19091,19091,19091,16,2020-04-23T23:00:00Z,2020-04-24T20:34:00Z,99ee3b71f0d0b08db02d4c91c8848257214ccebb
14,IL,39658,1.0,1.0,1.0,1.0,A,4.0,"Please stop using the ""total"" field. Use ""tota...",A,...,4/24 17:02,1795.0,NaN,189632,189632,189632,17,2020-04-24T04:00:00Z,2020-04-24T21:02:00Z,1d2178fff5d7da116ebe05b751d66ab87d33a3bd
15,IN,13680,1.0,1.0,1.0,0.0,B,3.0,"Please stop using the ""total"" field. Use ""tota...",C,...,4/24 16:49,741.0,NaN,75553,75553,75553,18,2020-04-24T03:59:00Z,2020-04-24T20:49:00Z,505939c77e616f7bb43f27dd6188167853a1d7c7
16,KS,2777,1.0,1.0,1.0,0.0,B,3.0,"Please stop using the ""total"" field. Use ""tota...",C,...,4/24 14:36,111.0,457.0,23588,23588,23588,20,2020-04-24T14:00:00Z,2020-04-24T18:36:00Z,28166949d5873cf8e289adfae854d426582d30b3
17,KY,3481,1.0,1.0,1.0,1.0,A,4.0,"Please stop using the ""total"" field. Use ""tota...",B,...,4/24 16:56,191.0,1115.0,42844,42844,42844,21,2020-04-23T21:00:00Z,2020-04-24T20:56:00Z,e59a544d45098a1e12657053f23d945d0c9e7dfe
18,LA,26140,1.0,1.0,1.0,1.0,A,4.0,"Please stop using the ""total"" field. Use ""tota...",C,...,4/24 15:18,1601.0,NaN,143716,143716,143716,22,2020-04-24T17:00:00Z,2020-04-24T19:18:00Z,59bf3192f8d2743c052a0402af7481889534467a
19,MA,46023,1.0,1.0,0.0,1.0,B,3.0,"Please stop using the ""total"" field. Use ""tota...",B,...,4/24 17:01,2360.0,4493.0,195076,195076,195076,25,2020-04-22T20:00:00Z,2020-04-24T21:01:00Z,48050435a4bb9c99a3ec0e28b45a2816f3e9389b
20,MD,16616,1.0,1.0,1.0,1.0,A,4.0,"Please stop using the ""total"" field. Use ""tota...",A,...,4/24 14:50,798.0,3618.0,84716,84716,84716,24,2020-04-24T14:00:00Z,2020-04-24T18:50:00Z,541d4142527bf28506d65d692c035c9001e07c81
21,ME,965,1.0,1.0,1.0,1.0,A,4.0,"Please stop using the ""total"" field. Use ""tota...",B,...,4/24 14:53,47.0,152.0,17749,17749,17749,23,2020-04-24T16:00:00Z,2020-04-24T18:53:00Z,ef2d85c1179ea6005a6b4a720660168e4ddc44e4
22,MI,36641,1.0,1.0,0.0,1.0,B,3.0,"Please stop using the ""total"" field. Use ""tota...",A+,...,4/24 16:17,3085.0,NaN,136296,136296,136296,26,2020-04-24T15:00:00Z,2020-04-24T20:17:00Z,905d69ef32e7c9c48c58810741902b25fa16ff42
23,MN,3185,1.0,1.0,1.0,1.0,A,4.0,"Please stop using the ""total"" field. Use ""tota...",A,...,4/24 17:03,221.0,756.0,53787,53787,53787,27,2020-04-23T21:00:00Z,2020-04-24T21:03:00Z,00dc74e49bd40417ded3fecf6fab75c2bea4325a
24,MO,6625,1.0,1.0,1.0,1.0,A,4.0,"Please stop using the ""total"" field. Use ""tota...",B,...,4/24 15:46,262.0,NaN,65207,65207,65207,29,2020-04-24T04:00:00Z,2020-04-24T19:46:00Z,ba00aa7b4d52578473d43f20aeb5acc65e262634
25,MS,5434,1.0,1.0,1.0,1.0,A,4.0,"Please stop using the ""total"" field. Use ""tota...",B,...,4/24 14:24,209.0,970.0,55670,55670,55670,28,2020-04-23T23:00:00Z,2020-04-24T18:24:00Z,31855a404742f759ddbd2fd0753f7db545aabad7
26,MT,444,1.0,1.0,1.0,1.0,A,4.0,"Please stop using the ""total"" field. Use ""tota...",D,...,4/24 14:27,14.0,59.0,12127,12127,12127,30,2020-04-24T04:00:00Z,2020-04-24T18:27:00Z,566fab36bf9df88c7f679dad4f444fcb3bfc94ee
27,NC,8052,1.0,1.0,1.0,1.0,A,4.0,"Please stop using the ""total"" field. Use ""tota...",C,...,4/24 14:29,269.0,NaN,100584,100584,100584,37,2020-04-24T15:00:00Z,2020-04-24T18:29:00Z,e342dccc249ce8a4a29bf47e4dc483e00ec62782
28,ND,748,1.0,1.0,1.0,0.0,B,3.0,"Please stop using the ""total"" field. Use ""tota...",C,...,4/24 14:31,15.0,67.0,17449,17449,17449,38,2020-04-24T17:00:00Z,2020-04-24T18:31:00Z,e387602a730a6ea01374c978fe48a5d38994132d
29,NE,2124,1.0,1.0,1.0,1.0,A,4.0,"Please stop using the ""total"" field. Use ""tota...",D,...,4/24 16:22,47.0,NaN,18612,18612,18612,31,2020-04-23T23:45:00Z,2020-04-24T20:22:00Z,2ae3485a37e82ad75950e816875c81e1aa6f7938
30,NH,1670,1.0,1.0,1.0,0.0,B,3.0,"Please stop using the ""total"" field. Use ""tota...",C,...,4/24 16:29,51.0,218.0,17233,16809,16809,33,2020-04-23T13:00:00Z,2020-04-24T20:29:00Z,1b1f3e7a33964d51d2efd9e344419417c6b6b9c3
31,NJ,102196,1.0,1.0,1.0,1.0,A,4.0,"Please stop using the ""total"" field. Use ""tota...",B,...,4/24 15:36,5617.0,NaN,205962,205962,205962,34,2020-04-24T17:00:00Z,2020-04-24T19:36:00Z,1571b1e37e19ba81945b782451d0b93365d7a965
32,NM,2379,1.0,1.0,1.0,1.0,A,4.0,"Please stop using the ""total"" field. Use ""tota...",C,...,4/24 14:35,78.0,367.0,46563,46563,46563,35,2020-04-24T14:28:00Z,2020-04-24T18:35:00Z,629cb0757cd925ddf784cefe0c9adeb6236cf899
33,NV,4398,1.0,1.0,1.0,1.0,A,4.0,"Please stop using the ""total"" field. Use ""tota...",F,...,4/24 14:36,197.0,NaN,36192,36192,36192,32,2020-04-24T14:00:00Z,2020-04-24T18:36:00Z,fd5320813fdf6e0d5fa137b2a79878b329490dca
34,NY,271590,1.0,1.0,1.0,1.0,A,4.0,"Please stop using the ""total"" field. Use ""tota...",B,...,4/24 17:02,16162.0,57103.0,730656,730656,730656,36,2020-04-24T04:00:00Z,2020-04-24T21:02:00Z,dd8a034f750ed97b500d70f9486ba8e4d211ce95
35,OH,14581,1.0,1.0,0.0,1.0,B,3.0,"Please stop using the ""total"" field. Use ""tota...",C,...,4/24 14:41,690.0,3053.0,107109,107109,107109,39,2020-04-24T18:00:00Z,2020-04-24T18:41:00Z,470c86be74d7f406e7cd95036b53af9704df22e3
36,OK,3121,1.0,1.0,0.0,1.0,B,3.0,"Please stop using the ""total"" field. Use ""tota...",A,...,4/24 14:49,188.0,637.0,46140,46140,46140,40,2020-04-24T04:00:00Z,2020-04-24T18:49:00Z,9d96d7f342f96a970d20e46bcc2a53164799e2c7
37,OR,2177,1.0,1.0,1.0,1.0,A,4.0,"Please stop using the ""total"" field. Use ""tota...",B,...,4/24 15:43,86.0,520.0,45492,45492,45492,41,2020-04-24T15:00:00Z,2020-04-24T19:43:00Z,46e184e3b01e531d4e4822388f1ce69df673de69
38,PA,38652,1.0,1.0,1.0,1.0,A,4.0,"Please stop using the ""total"" field. Use ""tota...",C,...,4/24 15:04,1492.0,NaN,186143,186143,186143,42,2020-04-24T04:00:00Z,2020-04-24T19:04:00Z,ec64936e14231f33bdbc73fec70ecaaca741a942
39,RI,6699,1.0,1.0,1.0,0.0,B,3.0,"Please stop using the ""total"" field. Use ""tota...",A+,...,4/24 16:01,202.0,576.0,47257,47257,47257,44,2020-04-24T16:00:00Z,2020-04-24T20:01:00Z,c421a8a6ef6cf3c13d799d9b3d9ad8d11a954735
40,SC,4917,1.0,1.0,1.0,0.0,B,3.0,"Please stop using the ""total"" field. Use ""tota...",B,...,4/24 16:20,150.0,837.0,44463,44463,44463,45,2020-04-23T03:59:00Z,2020-04-24T20:20:00Z,f1e6f56dfd887bb8ed21f7f2e4919176919c6851
41,SD,2040,1.0,1.0,1.0,1.0,A,4.0,"Please stop using the ""total"" field. Use ""tota...",C,...,4/24 15:13,10.0,124.0,14824,14824,14824,46,2020-04-23T22:00:00Z,2020-04-24T19:13:00Z,9a15eef836cb08da8b1a1b4494e6d35783c503df
42,TN,8726,1.0,1.0,1.0,1.0,A,4.0,"Please stop using the ""total"" field. Use ""tota...",C,...,4/24 16:07,168.0,808.0,131328,131328,131328,47,2020-04-23T19:00:00Z,2020-04-24T20:07:00Z,5dd248bba99c21304ca0b8c0636debb814e28bea
43,TX,22806,1.0,1.0,1.0,1.0,A,4.0,"Please stop using the ""total"" field. Use ""tota...",B,...,4/24 15:15,593.0,NaN,242547,242547,242547,48,2020-04-24T16:30:00Z,2020-04-24T19:15:00Z,5c41465a4430c04286353934a8ceaac1f337332e
44,UT,3782,1.0,1.0,1.0,1.0,A,4.0,"Please stop using the ""total"" field. Use ""tota...",C,...,4/24 15:47,39.0,315.0,84697,84697,84697,49,2020-04-24T19:00:00Z,2020-04-24T19:47:00Z,dd90fea90908217f9d8ab9eb5e83aee4511b24c7
45,VA,11169,1.0,1.0,1.0,1.0,A,4.0,"Please stop using the ""total"" field. Use ""tota...",B,...,4/24 16:57,410.0,1837.0,69502,69015,69015,51,2020-04-24T04:00:00Z,2020-04-24T20:57:00Z,5f7551baa9437df6b1c352dbac65c7d94b021d85
46,VT,827,1.0,1.0,1.0,1.0,A,4.0,"Please stop using the ""total"" field. Use ""tota...",C,...,4/24 15:33,44.0,NaN,14310,14310,14310,50,2020-04-24T13:46:00Z,2020-04-24T19:33:00Z,9c07f31358aaacef0f578ae8c9cd9fa68927e3ce
47,WA,12753,0.0,1.0,0.0,1.0,C,2.0,"Please stop using the ""total"" field. Use ""tota...",C,...,4/24 16:53,711.0,NaN,153376,153376,153376,53,2020-04-23T06:59:00Z,2020-04-24T20:53:00Z,14b7b5e866adddf27b056b9bc3f089c0ef4b00ec
48,WI,5356,1.0,1.0,1.0,1.0,A,4.0,"Please stop using the ""total"" field. Use ""tota...",A,...,4/24 16:51,262.0,1353.0,60135,59929,59929,55,2020-04-24T20:00:00Z,2020-04-24T20:51:00Z,93c1665444dcac7c0270eb9db97749817f59d6bf
49,WV,988,1.0,1.0,1.0,0.0,B,3.0,"Please stop using the ""total"" field. Use ""tota...",B,...,4/24 16:44,32.0,NaN,29811,29811,29811,54,2020-04-24T14:00:00Z,2020-04-24T20:44:00Z,5f1abb472e1d9025b5aba4a3414576a3e237ec35
50,WY,349,1.0,1.0,1.0,1.0,A,4.0,"Please stop using the ""total"" field. Use ""tota...",D,...,4/24 17:05,7.0,54.0,8045,8045,8045,56,2020-04-23T21:26:00Z,2020-04-24T21:05:00Z,84a75c4750c8063bb10464f983bdd2faae7d4ef6
51,PR,1276,1.0,1.0,1.0,1.0,A,4.0,"Please stop using the ""total"" field. Use ""tota...",D,...,4/24 15:11,77.0,NaN,12529,10589,10589,72,2020-04-24T10:30:00Z,2020-04-24T19:11:00Z,f7f23d30f115057f972c28bbf3275c944c966c83
52,AS,0,NaN,NaN,NaN,NaN,NaN,NaN,"Please stop using the ""total"" field. Use ""tota...",F,...,4/24 14:10,NaN,NaN,20,3,3,60,2020-04-06T04:00:00Z,2020-04-24T18:10:00Z,12191980526f2f21e5d8a0863468ffeed9e8776c
53,GU,141,NaN,NaN,NaN,NaN,NaN,NaN,"Please stop using the ""total"" field. Use ""tota...",D,...,4/24 16:39,5.0,NaN,1374,1374,1374,66,2020-04-24T11:40:00Z,2020-04-24T20:39:00Z,a555664c8cdbd288357e2a0032b7d9abc3e590af
54,MP,14,NaN,NaN,NaN,NaN,NaN,NaN,"Please stop using the ""total"" field. Use ""tota...",D,...,4/24 16:08,2.0,NaN,65,65,65,69,2020-04-24T04:00:00Z,2020-04-24T20:08:00Z,9d3d9c5668a4eb1441354652adaeba3b5c8b2f78
55,VI,54,NaN,NaN,NaN,NaN,NaN,NaN,"Please stop using the ""total"" field. Use ""tota...",D,...,4/24 14:17,3.0,NaN,731,696,696,78,2020-04-23T04:00:00Z,2020-04-24T18:17:00Z,565ad2d572fd5dc0979ac65a70259e1ba7ad9b4f

In [29]:
df.columns

Index(['state', 'positive', 'positiveScore', 'negativeScore',
       'negativeRegularScore', 'commercialScore', 'grade', 'score', 'notes',
       'dataQualityGrade', 'negative', 'pending', 'hospitalizedCurrently',
       'hospitalizedCumulative', 'inIcuCurrently', 'inIcuCumulative',
       'onVentilatorCurrently', 'onVentilatorCumulative', 'recovered',
       'lastUpdateEt', 'checkTimeEt', 'death', 'hospitalized', 'total',
       'totalTestResults', 'posNeg', 'fips', 'dateModified', 'dateChecked',
       'hash'],
      dtype='object')

In [18]:
type(df.columns)

pandas.core.indexes.base.Index

In [28]:
df.columns.tolist()

['state',
 'positive',
 'positiveScore',
 'negativeScore',
 'negativeRegularScore',
 'commercialScore',
 'grade',
 'score',
 'notes',
 'dataQualityGrade',
 'negative',
 'pending',
 'hospitalizedCurrently',
 'hospitalizedCumulative',
 'inIcuCurrently',
 'inIcuCumulative',
 'onVentilatorCurrently',
 'onVentilatorCumulative',
 'recovered',
 'lastUpdateEt',
 'checkTimeEt',
 'death',
 'hospitalized',
 'total',
 'totalTestResults',
 'posNeg',
 'fips',
 'dateModified',
 'dateChecked',
 'hash']

In [32]:
df.head
df.tail

<bound method NDFrame.tail of    state  positive  positiveScore  negativeScore  negativeRegularScore  \
0     AK       339            1.0            1.0                   1.0
1     AL      5832            1.0            1.0                   0.0
2     AR      2741            1.0            1.0                   1.0
3     AZ      6045            1.0            1.0                   0.0
4     CA     39254            1.0            1.0                   0.0
5     CO     11262            1.0            1.0                   1.0
6     CT     23921            1.0            1.0                   1.0
7     DC      3528            1.0            1.0                   1.0
8     DE      3442            1.0            1.0                   1.0
9     FL     30174            1.0            1.0                   1.0
10    GA     22147            1.0            1.0                   1.0
11    HI       596            1.0            1.0                   1.0
12    IA      4445            1.0            1.0                   1.0
13    ID      1836            1.0            1.0                   1.0
14    IL     39658            1.0            1.0                   1.0
15    IN     13680            1.0            1.0                   1.0
16    KS      2777            1.0            1.0                   1.0
17    KY      3481            1.0            1.0                   1.0
18    LA     26140            1.0            1.0                   1.0
19    MA     46023            1.0            1.0                   0.0
20    MD     16616            1.0            1.0                   1.0
21    ME       965            1.0            1.0                   1.0
22    MI     36641            1.0            1.0                   0.0
23    MN      3185            1.0            1.0                   1.0
24    MO      6625            1.0            1.0                   1.0
25    MS      5434            1.0            1.0                   1.0
26    MT       444            1.0            1.0                   1.0
27    NC      8052            1.0            1.0                   1.0
28    ND       748            1.0            1.0                   1.0
29    NE      2124            1.0            1.0                   1.0
30    NH      1670            1.0            1.0                   1.0
31    NJ    102196            1.0            1.0                   1.0
32    NM      2379            1.0            1.0                   1.0
33    NV      4398            1.0            1.0                   1.0
34    NY    271590            1.0            1.0                   1.0
35    OH     14581            1.0            1.0                   0.0
36    OK      3121            1.0            1.0                   0.0
37    OR      2177            1.0            1.0                   1.0
38    PA     38652            1.0            1.0                   1.0
39    RI      6699            1.0            1.0                   1.0
40    SC      4917            1.0            1.0                   1.0
41    SD      2040            1.0            1.0                   1.0
42    TN      8726            1.0            1.0                   1.0
43    TX     22806            1.0            1.0                   1.0
44    UT      3782            1.0            1.0                   1.0
45    VA     11169            1.0            1.0                   1.0
46    VT       827            1.0            1.0                   1.0
47    WA     12753            0.0            1.0                   0.0
48    WI      5356            1.0            1.0                   1.0
49    WV       988            1.0            1.0                   1.0
50    WY       349            1.0            1.0                   1.0
51    PR      1276            1.0            1.0                   1.0
52    AS         0            NaN            NaN                   NaN
53    GU       141            NaN            NaN                   NaN
54    MP        14            NaN            NaN                   NaN
55    VI        54            NaN            NaN                   NaN

    commercialScore grade  score  \
0               1.0     A    4.0
1               1.0     B    3.0
2               1.0     A    4.0
3               1.0     B    3.0
4               1.0     B    3.0
5               1.0     A    4.0
6               1.0     A    4.0
7               1.0     A    4.0
8               1.0     A    4.0
9               1.0     A    4.0
10              1.0     A    4.0
11              1.0     A    4.0
12              1.0     A    4.0
13              1.0     A    4.0
14              1.0     A    4.0
15              0.0     B    3.0
16              0.0     B    3.0
17              1.0     A    4.0
18              1.0     A    4.0
19              1.0     B    3.0
20              1.0     A    4.0
21              1.0     A    4.0
22              1.0     B    3.0
23              1.0     A    4.0
24              1.0     A    4.0
25              1.0     A    4.0
26              1.0     A    4.0
27              1.0     A    4.0
28              0.0     B    3.0
29              1.0     A    4.0
30              0.0     B    3.0
31              1.0     A    4.0
32              1.0     A    4.0
33              1.0     A    4.0
34              1.0     A    4.0
35              1.0     B    3.0
36              1.0     B    3.0
37              1.0     A    4.0
38              1.0     A    4.0
39              0.0     B    3.0
40              0.0     B    3.0
41              1.0     A    4.0
42              1.0     A    4.0
43              1.0     A    4.0
44              1.0     A    4.0
45              1.0     A    4.0
46              1.0     A    4.0
47              1.0     C    2.0
48              1.0     A    4.0
49              0.0     B    3.0
50              1.0     A    4.0
51              1.0     A    4.0
52              NaN   NaN    NaN
53              NaN   NaN    NaN
54              NaN   NaN    NaN
55              NaN   NaN    NaN

                                                notes dataQualityGrade  ...  \
0   Please stop using the "total" field. Use "tota...                B  ...
1   Please stop using the "total" field. Use "tota...                B  ...
2   Please stop using the "total" field. Use "tota...                B  ...
3   Please stop using the "total" field. Use "tota...               A+  ...
4   Please stop using the "total" field. Use "tota...                B  ...
5   Please stop using the "total" field. Use "tota...                C  ...
6   Please stop using the "total" field. Use "tota...                C  ...
7   Please stop using the "total" field. Use "tota...               A+  ...
8   Please stop using the "total" field. Use "tota...                C  ...
9   Please stop using the "total" field. Use "tota...                C  ...
10  Please stop using the "total" field. Use "tota...                B  ...
11  Please stop using the "total" field. Use "tota...                D  ...
12  Please stop using the "total" field. Use "tota...                B  ...
13  Please stop using the "total" field. Use "tota...                C  ...
14  Please stop using the "total" field. Use "tota...                A  ...
15  Please stop using the "total" field. Use "tota...                C  ...
16  Please stop using the "total" field. Use "tota...                C  ...
17  Please stop using the "total" field. Use "tota...                B  ...
18  Please stop using the "total" field. Use "tota...                C  ...
19  Please stop using the "total" field. Use "tota...                B  ...
20  Please stop using the "total" field. Use "tota...                A  ...
21  Please stop using the "total" field. Use "tota...                B  ...
22  Please stop using the "total" field. Use "tota...               A+  ...
23  Please stop using the "total" field. Use "tota...                A  ...
24  Please stop using the "total" field. Use "tota...                B  ...
25  Please stop using the "total" field. Use "tota...                B  ...
26  Please stop using the "total" field. Use "tota...                D  ...
27  Please stop using the "total" field. Use "tota...                C  ...
28  Please stop using the "total" field. Use "tota...                C  ...
29  Please stop using the "total" field. Use "tota...                D  ...
30  Please stop using the "total" field. Use "tota...                C  ...
31  Please stop using the "total" field. Use "tota...                B  ...
32  Please stop using the "total" field. Use "tota...                C  ...
33  Please stop using the "total" field. Use "tota...                F  ...
34  Please stop using the "total" field. Use "tota...                B  ...
35  Please stop using the "total" field. Use "tota...                C  ...
36  Please stop using the "total" field. Use "tota...                A  ...
37  Please stop using the "total" field. Use "tota...                B  ...
38  Please stop using the "total" field. Use "tota...                C  ...
39  Please stop using the "total" field. Use "tota...               A+  ...
40  Please stop using the "total" field. Use "tota...                B  ...
41  Please stop using the "total" field. Use "tota...                C  ...
42  Please stop using the "total" field. Use "tota...                C  ...
43  Please stop using the "total" field. Use "tota...                B  ...
44  Please stop using the "total" field. Use "tota...                C  ...
45  Please stop using the "total" field. Use "tota...                B  ...
46  Please stop using the "total" field. Use "tota...                C  ...
47  Please stop using the "total" field. Use "tota...                C  ...
48  Please stop using the "total" field. Use "tota...                A  ...
49  Please stop using the "total" field. Use "tota...                B  ...
50  Please stop using the "total" field. Use "tota...                D  ...
51  Please stop using the "total" field. Use "tota...                D  ...
52  Please stop using the "total" field. Use "tota...                F  ...
53  Please stop using the "total" field. Use "tota...                D  ...
54  Please stop using the "total" field. Use "tota...                D  ...
55  Please stop using the "total" field. Use "tota...                D  ...

    checkTimeEt    death  hospitalized   total  totalTestResults  posNeg  \
0    4/24 16:02      9.0           NaN   12281             12281   12281
1    4/24 16:05    197.0         768.0   52695             52695   52695
2    4/24 15:42     45.0         291.0   35578             35578   35578
3    4/24 15:39    266.0         984.0   60714             60714   60714
4    4/24 17:00   1562.0           NaN  494173            494173  494173
5    4/24 15:52    552.0        2237.0   52324             52324   52324
6    4/24 17:03   1764.0           NaN   74038             74038   74038
7    4/24 16:11    153.0           NaN   16533             16533   16533
8    4/24 16:16    100.0           NaN   17379             17379   17379
9    4/24 16:23   1031.0        4888.0  318246            316959  316959
10   4/24 16:26    892.0        4221.0  107176            107176  107176
11   4/24 15:40     12.0          63.0   26887             26887   26887
12   4/24 15:03    107.0           NaN   31973             31973   31973
13   4/24 16:34     54.0         166.0   19091             19091   19091
14   4/24 17:02   1795.0           NaN  189632            189632  189632
15   4/24 16:49    741.0           NaN   75553             75553   75553
16   4/24 14:36    111.0         457.0   23588             23588   23588
17   4/24 16:56    191.0        1115.0   42844             42844   42844
18   4/24 15:18   1601.0           NaN  143716            143716  143716
19   4/24 17:01   2360.0        4493.0  195076            195076  195076
20   4/24 14:50    798.0        3618.0   84716             84716   84716
21   4/24 14:53     47.0         152.0   17749             17749   17749
22   4/24 16:17   3085.0           NaN  136296            136296  136296
23   4/24 17:03    221.0         756.0   53787             53787   53787
24   4/24 15:46    262.0           NaN   65207             65207   65207
25   4/24 14:24    209.0         970.0   55670             55670   55670
26   4/24 14:27     14.0          59.0   12127             12127   12127
27   4/24 14:29    269.0           NaN  100584            100584  100584
28   4/24 14:31     15.0          67.0   17449             17449   17449
29   4/24 16:22     47.0           NaN   18612             18612   18612
30   4/24 16:29     51.0         218.0   17233             16809   16809
31   4/24 15:36   5617.0           NaN  205962            205962  205962
32   4/24 14:35     78.0         367.0   46563             46563   46563
33   4/24 14:36    197.0           NaN   36192             36192   36192
34   4/24 17:02  16162.0       57103.0  730656            730656  730656
35   4/24 14:41    690.0        3053.0  107109            107109  107109
36   4/24 14:49    188.0         637.0   46140             46140   46140
37   4/24 15:43     86.0         520.0   45492             45492   45492
38   4/24 15:04   1492.0           NaN  186143            186143  186143
39   4/24 16:01    202.0         576.0   47257             47257   47257
40   4/24 16:20    150.0         837.0   44463             44463   44463
41   4/24 15:13     10.0         124.0   14824             14824   14824
42   4/24 16:07    168.0         808.0  131328            131328  131328
43   4/24 15:15    593.0           NaN  242547            242547  242547
44   4/24 15:47     39.0         315.0   84697             84697   84697
45   4/24 16:57    410.0        1837.0   69502             69015   69015
46   4/24 15:33     44.0           NaN   14310             14310   14310
47   4/24 16:53    711.0           NaN  153376            153376  153376
48   4/24 16:51    262.0        1353.0   60135             59929   59929
49   4/24 16:44     32.0           NaN   29811             29811   29811
50   4/24 17:05      7.0          54.0    8045              8045    8045
51   4/24 15:11     77.0           NaN   12529             10589   10589
52   4/24 14:10      NaN           NaN      20                 3       3
53   4/24 16:39      5.0           NaN    1374              1374    1374
54   4/24 16:08      2.0           NaN      65                65      65
55   4/24 14:17      3.0           NaN     731               696     696

    fips          dateModified           dateChecked  \
0     02  2020-04-24T19:00:00Z  2020-04-24T20:02:00Z
1     01  2020-04-24T04:00:00Z  2020-04-24T20:05:00Z
2     05  2020-04-24T14:47:00Z  2020-04-24T19:42:00Z
3     04  2020-04-24T04:00:00Z  2020-04-24T19:39:00Z
4     06  2020-04-23T04:00:00Z  2020-04-24T21:00:00Z
5     08  2020-04-23T04:00:00Z  2020-04-24T19:52:00Z
6     09  2020-04-24T20:00:00Z  2020-04-24T21:03:00Z
7     11  2020-04-23T04:00:00Z  2020-04-24T20:11:00Z
8     10  2020-04-23T22:00:00Z  2020-04-24T20:16:00Z
9     12  2020-04-24T13:41:00Z  2020-04-24T20:23:00Z
10    13  2020-04-24T15:28:00Z  2020-04-24T20:26:00Z
11    15  2020-04-23T22:00:00Z  2020-04-24T19:40:00Z
12    19  2020-04-23T16:00:00Z  2020-04-24T19:03:00Z
13    16  2020-04-23T23:00:00Z  2020-04-24T20:34:00Z
14    17  2020-04-24T04:00:00Z  2020-04-24T21:02:00Z
15    18  2020-04-24T03:59:00Z  2020-04-24T20:49:00Z
16    20  2020-04-24T14:00:00Z  2020-04-24T18:36:00Z
17    21  2020-04-23T21:00:00Z  2020-04-24T20:56:00Z
18    22  2020-04-24T17:00:00Z  2020-04-24T19:18:00Z
19    25  2020-04-22T20:00:00Z  2020-04-24T21:01:00Z
20    24  2020-04-24T14:00:00Z  2020-04-24T18:50:00Z
21    23  2020-04-24T16:00:00Z  2020-04-24T18:53:00Z
22    26  2020-04-24T15:00:00Z  2020-04-24T20:17:00Z
23    27  2020-04-23T21:00:00Z  2020-04-24T21:03:00Z
24    29  2020-04-24T04:00:00Z  2020-04-24T19:46:00Z
25    28  2020-04-23T23:00:00Z  2020-04-24T18:24:00Z
26    30  2020-04-24T04:00:00Z  2020-04-24T18:27:00Z
27    37  2020-04-24T15:00:00Z  2020-04-24T18:29:00Z
28    38  2020-04-24T17:00:00Z  2020-04-24T18:31:00Z
29    31  2020-04-23T23:45:00Z  2020-04-24T20:22:00Z
30    33  2020-04-23T13:00:00Z  2020-04-24T20:29:00Z
31    34  2020-04-24T17:00:00Z  2020-04-24T19:36:00Z
32    35  2020-04-24T14:28:00Z  2020-04-24T18:35:00Z
33    32  2020-04-24T14:00:00Z  2020-04-24T18:36:00Z
34    36  2020-04-24T04:00:00Z  2020-04-24T21:02:00Z
35    39  2020-04-24T18:00:00Z  2020-04-24T18:41:00Z
36    40  2020-04-24T04:00:00Z  2020-04-24T18:49:00Z
37    41  2020-04-24T15:00:00Z  2020-04-24T19:43:00Z
38    42  2020-04-24T04:00:00Z  2020-04-24T19:04:00Z
39    44  2020-04-24T16:00:00Z  2020-04-24T20:01:00Z
40    45  2020-04-23T03:59:00Z  2020-04-24T20:20:00Z
41    46  2020-04-23T22:00:00Z  2020-04-24T19:13:00Z
42    47  2020-04-23T19:00:00Z  2020-04-24T20:07:00Z
43    48  2020-04-24T16:30:00Z  2020-04-24T19:15:00Z
44    49  2020-04-24T19:00:00Z  2020-04-24T19:47:00Z
45    51  2020-04-24T04:00:00Z  2020-04-24T20:57:00Z
46    50  2020-04-24T13:46:00Z  2020-04-24T19:33:00Z
47    53  2020-04-23T06:59:00Z  2020-04-24T20:53:00Z
48    55  2020-04-24T20:00:00Z  2020-04-24T20:51:00Z
49    54  2020-04-24T14:00:00Z  2020-04-24T20:44:00Z
50    56  2020-04-23T21:26:00Z  2020-04-24T21:05:00Z
51    72  2020-04-24T10:30:00Z  2020-04-24T19:11:00Z
52    60  2020-04-06T04:00:00Z  2020-04-24T18:10:00Z
53    66  2020-04-24T11:40:00Z  2020-04-24T20:39:00Z
54    69  2020-04-24T04:00:00Z  2020-04-24T20:08:00Z
55    78  2020-04-23T04:00:00Z  2020-04-24T18:17:00Z

                                        hash
0   829ac690ed4c16079a6f1890fcf8105935a055ff
1   45ada0943397a4f5bd08772ab110f0594bbc7e02
2   e70e363b75b64ad74efd0b6d046672c6e818750b
3   72d72c4092636c2a96a366a5895055feccc0aeef
4   0711cfd3633ed6d50a0d5f33573f8929f3dfaed2
5   80390462b00d2eb665810b44b4eebe90c50be35f
6   7d8a5fbd78b7fa19f6e713f22383c9dca80f57bf
7   b201fd045daf11cb21270054ea3737ae58c477dd
8   e31ad6975732e8bf659a2bed46637352717e95be
9   839baf0394d82f4a72040ed93679d35b0ea391ea
10  44f24ebc70052d04096a3ecf7a7b3361ec895955
11  4054a6bc0decc1a1ae7c6a9db191f28733c1d24e
12  a6033303518fbb5a992ba4f813170fab77b90525
13  99ee3b71f0d0b08db02d4c91c8848257214ccebb
14  1d2178fff5d7da116ebe05b751d66ab87d33a3bd
15  505939c77e616f7bb43f27dd6188167853a1d7c7
16  28166949d5873cf8e289adfae854d426582d30b3
17  e59a544d45098a1e12657053f23d945d0c9e7dfe
18  59bf3192f8d2743c052a0402af7481889534467a
19  48050435a4bb9c99a3ec0e28b45a2816f3e9389b
20  541d4142527bf28506d65d692c035c9001e07c81
21  ef2d85c1179ea6005a6b4a720660168e4ddc44e4
22  905d69ef32e7c9c48c58810741902b25fa16ff42
23  00dc74e49bd40417ded3fecf6fab75c2bea4325a
24  ba00aa7b4d52578473d43f20aeb5acc65e262634
25  31855a404742f759ddbd2fd0753f7db545aabad7
26  566fab36bf9df88c7f679dad4f444fcb3bfc94ee
27  e342dccc249ce8a4a29bf47e4dc483e00ec62782
28  e387602a730a6ea01374c978fe48a5d38994132d
29  2ae3485a37e82ad75950e816875c81e1aa6f7938
30  1b1f3e7a33964d51d2efd9e344419417c6b6b9c3
31  1571b1e37e19ba81945b782451d0b93365d7a965
32  629cb0757cd925ddf784cefe0c9adeb6236cf899
33  fd5320813fdf6e0d5fa137b2a79878b329490dca
34  dd8a034f750ed97b500d70f9486ba8e4d211ce95
35  470c86be74d7f406e7cd95036b53af9704df22e3
36  9d96d7f342f96a970d20e46bcc2a53164799e2c7
37  46e184e3b01e531d4e4822388f1ce69df673de69
38  ec64936e14231f33bdbc73fec70ecaaca741a942
39  c421a8a6ef6cf3c13d799d9b3d9ad8d11a954735
40  f1e6f56dfd887bb8ed21f7f2e4919176919c6851
41  9a15eef836cb08da8b1a1b4494e6d35783c503df
42  5dd248bba99c21304ca0b8c0636debb814e28bea
43  5c41465a4430c04286353934a8ceaac1f337332e
44  dd90fea90908217f9d8ab9eb5e83aee4511b24c7
45  5f7551baa9437df6b1c352dbac65c7d94b021d85
46  9c07f31358aaacef0f578ae8c9cd9fa68927e3ce
47  14b7b5e866adddf27b056b9bc3f089c0ef4b00ec
48  93c1665444dcac7c0270eb9db97749817f59d6bf
49  5f1abb472e1d9025b5aba4a3414576a3e237ec35
50  84a75c4750c8063bb10464f983bdd2faae7d4ef6
51  f7f23d30f115057f972c28bbf3275c944c966c83
52  12191980526f2f21e5d8a0863468ffeed9e8776c
53  a555664c8cdbd288357e2a0032b7d9abc3e590af

In [33]:
df.index

RangeIndex(start=0, stop=56, step=1)

In [34]:
df_numpy = df.to_numpy()

In [37]:
df_numpy

array([['AK', 339, 1.0, ..., '2020-04-24T19:00:00Z',
        '2020-04-24T20:02:00Z',
        '829ac690ed4c16079a6f1890fcf8105935a055ff'],
       ['AL', 5832, 1.0, ..., '2020-04-24T04:00:00Z',
        '2020-04-24T20:05:00Z',
        '45ada0943397a4f5bd08772ab110f0594bbc7e02'],
       ['AR', 2741, 1.0, ..., '2020-04-24T14:47:00Z',
        '2020-04-24T19:42:00Z',
        'e70e363b75b64ad74efd0b6d046672c6e818750b'],
       ...,
       ['GU', 141, nan, ..., '2020-04-24T11:40:00Z',
        '2020-04-24T20:39:00Z',
        'a555664c8cdbd288357e2a0032b7d9abc3e590af'],
       ['MP', 14, nan, ..., '2020-04-24T04:00:00Z',
        '2020-04-24T20:08:00Z',
        '9d3d9c5668a4eb1441354652adaeba3b5c8b2f78'],
       ['VI', 54, nan, ..., '2020-04-23T04:00:00Z',
        '2020-04-24T18:17:00Z',
        '565ad2d572fd5dc0979ac65a70259e1ba7ad9b4f']], dtype=object)

In [38]:
type(df.index)

pandas.core.indexes.range.RangeIndex

In [40]:
help(df.index)

Help on RangeIndex in module pandas.core.indexes.range object:

class RangeIndex(pandas.core.indexes.numeric.Int64Index)
 |  RangeIndex(start=None, stop=None, step=None, dtype=None, copy=False, name=None)
 |
 |  Immutable Index implementing a monotonic integer range.
 |
 |  RangeIndex is a memory-saving special case of Int64Index limited to
 |  representing monotonic ranges. Using RangeIndex may in some instances
 |  improve computing speed.
 |
 |  This is the default index type used
 |  by DataFrame and Series when no explicit index is provided by the user.
 |
 |  Parameters
 |  ----------
 |  start : int (default: 0), or other RangeIndex instance
 |      If int and "stop" is not given, interpreted as "stop" instead.
 |  stop : int (default: 0)
 |  step : int (default: 1)
 |  name : object, optional
 |      Name to be stored in the index.
 |  copy : bool, default False
 |      Unused, accepted for homogeneity with other index types.
 |
 |  Attributes
 |  ----------
 |  start
 |  stop
 |  step
 |
 |  Methods
 |  -------
 |  from_range
 |
 |  See Also
 |  --------
 |  Index : The base pandas Index type.
 |  Int64Index : Index of int64 data.
 |
 |  Method resolution order:
 |      RangeIndex
 |      pandas.core.indexes.numeric.Int64Index
 |      pandas.core.indexes.numeric.IntegerIndex
 |      pandas.core.indexes.numeric.NumericIndex
 |      pandas.core.indexes.base.Index
 |      pandas.core.base.IndexOpsMixin
 |      pandas.core.base.PandasObject
 |      pandas.core.accessor.DirNamesMixin
 |      builtins.object
 |
 |  Methods defined here:
 |
 |  __abs__(self)
 |
 |  __add__(self, other)
 |
 |  __contains__(self, key: Union[int, numpy.integer]) -> bool
 |      Check if key is a float and has a decimal. If it has, return False.
 |
 |  __floordiv__(self, other)
 |
 |  __getitem__(self, key)
 |      Conserve RangeIndex type for scalar and slice keys.
 |
 |  __inv__(self)
 |
 |  __len__(self) -> int
 |      return the length of the RangeIndex
 |
 |  __mul__(self, other)
 |
 |  __neg__(self)
 |
 |  __pos__(self)
 |
 |  __radd__(self, other)
 |
 |  __reduce__(self)
 |      Helper for pickle.
 |
 |  __rmul__(self, other)
 |
 |  __rsub__(self, other)
 |
 |  __rtruediv__(self, other)
 |
 |  __sub__(self, other)
 |
 |  __truediv__(self, other)
 |
 |  all(self) -> bool
 |      Return whether all elements are True.
 |
 |      Parameters
 |      ----------
 |      *args
 |          These parameters will be passed to numpy.all.
 |      **kwargs
 |          These parameters will be passed to numpy.all.
 |
 |      Returns
 |      -------
 |      all : bool or array_like (if axis is specified)
 |          A single element array_like may be converted to bool.
 |
 |      See Also
 |      --------
 |      Index.any : Return whether any element in an Index is True.
 |      Series.any : Return whether any element in a Series is True.
 |      Series.all : Return whether all elements in a Series are True.
 |
 |      Notes
 |      -----
 |      Not a Number (NaN), positive infinity and negative infinity
 |      evaluate to True because these are not equal to zero.
 |
 |      Examples
 |      --------
 |      **all**
 |
 |      True, because nonzero integers are considered True.
 |
 |      >>> pd.Index([1, 2, 3]).all()
 |      True
 |
 |      False, because ``0`` is considered False.
 |
 |      >>> pd.Index([0, 1, 2]).all()
 |      False
 |
 |      **any**
 |
 |      True, because ``1`` is considered True.
 |
 |      >>> pd.Index([0, 0, 1]).any()
 |      True
 |
 |      False, because ``0`` is considered False.
 |
 |      >>> pd.Index([0, 0, 0]).any()
 |      False
 |
 |  any(self) -> bool
 |      Return whether any element is True.
 |
 |      Parameters
 |      ----------
 |      *args
 |          These parameters will be passed to numpy.any.
 |      **kwargs
 |          These parameters will be passed to numpy.any.
 |
 |      Returns
 |      -------
 |      any : bool or array_like (if axis is specified)
 |          A single element array_like may be converted to bool.
 |
 |      See Also
 |      --------
 |      Index.all : Return whether all elements are True.
 |      Series.all : Return whether all elements are True.
 |
 |      Notes
 |      -----
 |      Not a Number (NaN), positive infinity and negative infinity
 |      evaluate to True because these are not equal to zero.
 |
 |      Examples
 |      --------
 |      >>> index = pd.Index([0, 1, 2])
 |      >>> index.any()
 |      True
 |
 |      >>> index = pd.Index([0, 0, 0])
 |      >>> index.any()
 |      False
 |
 |  argsort(self, *args, **kwargs)
 |      Returns the indices that would sort the index and its
 |      underlying data.
 |
 |      Returns
 |      -------
 |      argsorted : numpy array
 |
 |      See Also
 |      --------
 |      numpy.ndarray.argsort
 |
 |  copy(self, name=None, deep=False, dtype=None, **kwargs)
 |      Make a copy of this object.  Name and dtype sets those attributes on
 |      the new object.
 |
 |      Parameters
 |      ----------
 |      name : str, optional
 |      deep : bool, default False
 |      dtype : numpy dtype or pandas type
 |
 |      Returns
 |      -------
 |      copy : Index
 |
 |      Notes
 |      -----
 |      In most cases, there should be no functional difference from using
 |      ``deep``, but if ``deep`` is passed it will attempt to deepcopy.
 |
 |  equals(self, other)
 |      Determines if two Index objects contain the same elements.
 |
 |  get_indexer(self, target, method=None, limit=None, tolerance=None)
 |      Compute indexer and mask for new index given the current index. The
 |      indexer should be then used as an input to ndarray.take to align the
 |      current data to the new index.
 |
 |      Parameters
 |      ----------
 |      target : %(target_klass)s
 |      method : {None, 'pad'/'ffill', 'backfill'/'bfill', 'nearest'}, optional
 |          * default: exact matches only.
 |          * pad / ffill: find the PREVIOUS index value if no exact match.
 |          * backfill / bfill: use NEXT index value if no exact match
 |          * nearest: use the NEAREST index value if no exact match. Tied
 |            distances are broken by preferring the larger index value.
 |      limit : int, optional
 |          Maximum number of consecutive labels in ``target`` to match for
 |          inexact matches.
 |      tolerance : optional
 |          Maximum distance between original and new labels for inexact
 |          matches. The values of the index at the matching locations most
 |          satisfy the equation ``abs(index[indexer] - target) <= tolerance``.
 |
 |          Tolerance may be a scalar value, which applies the same tolerance
 |          to all values, or list-like, which applies variable tolerance per
 |          element. List-like includes list, tuple, array, Series, and must be
 |          the same size as the index and its dtype must exactly match the
 |          index's type.
 |
 |          .. versionadded:: 0.21.0 (list-like tolerance)
 |
 |      Returns
 |      -------
 |      indexer : ndarray of int
 |          Integers from 0 to n - 1 indicating that the index at these
 |          positions matches the corresponding target values. Missing values
 |          in the target are marked by -1.
 |      %(raises_section)s
 |      Examples
 |      --------
 |      >>> index = pd.Index(['c', 'a', 'b'])
 |      >>> index.get_indexer(['a', 'b', 'x'])
 |      array([ 1,  2, -1])
 |
 |      Notice that the return value is an array of locations in ``index``
 |      and ``x`` is marked by -1, as it is not in ``index``.
 |
 |  get_loc(self, key, method=None, tolerance=None)
 |      Get integer location, slice or boolean mask for requested label.
 |
 |      Parameters
 |      ----------
 |      key : label
 |      method : {None, 'pad'/'ffill', 'backfill'/'bfill', 'nearest'}, optional
 |          * default: exact matches only.
 |          * pad / ffill: find the PREVIOUS index value if no exact match.
 |          * backfill / bfill: use NEXT index value if no exact match
 |          * nearest: use the NEAREST index value if no exact match. Tied
 |            distances are broken by preferring the larger index value.
 |      tolerance : int or float, optional
 |          Maximum distance from index value for inexact matches. The value of
 |          the index at the matching location most satisfy the equation
 |          ``abs(index[loc] - key) <= tolerance``.
 |
 |          .. versionadded:: 0.21.0 (list-like tolerance)
 |
 |      Returns
 |      -------
 |      loc : int if unique index, slice if monotonic index, else mask
 |
 |      Examples
 |      --------
 |      >>> unique_index = pd.Index(list('abc'))
 |      >>> unique_index.get_loc('b')
 |      1
 |
 |      >>> monotonic_index = pd.Index(list('abbc'))
 |      >>> monotonic_index.get_loc('b')
 |      slice(1, 3, None)
 |
 |      >>> non_monotonic_index = pd.Index(list('abcb'))
 |      >>> non_monotonic_index.get_loc('b')
 |      array([False,  True, False,  True], dtype=bool)
 |
 |  intersection(self, other, sort=False)
 |      Form the intersection of two Index objects.
 |
 |      Parameters
 |      ----------
 |      other : Index or array-like
 |      sort : False or None, default False
 |          Sort the resulting index if possible
 |
 |          .. versionadded:: 0.24.0
 |
 |          .. versionchanged:: 0.24.1
 |
 |             Changed the default to ``False`` to match the behaviour
 |             from before 0.24.0.
 |
 |      Returns
 |      -------
 |      intersection : Index
 |
 |  join(self, other, how='left', level=None, return_indexers=False, sort=False)
 |      Compute join_index and indexers to conform data
 |      structures to the new index.
 |
 |      Parameters
 |      ----------
 |      other : Index
 |      how : {'left', 'right', 'inner', 'outer'}
 |      level : int or level name, default None
 |      return_indexers : bool, default False
 |      sort : bool, default False
 |          Sort the join keys lexicographically in the result Index. If False,
 |          the order of the join keys depends on the join type (how keyword).
 |
 |      Returns
 |      -------
 |      join_index, (left_indexer, right_indexer)
 |
 |  max(self, axis=None, skipna=True, *args, **kwargs)
 |      The maximum value of the RangeIndex
 |
 |  memory_usage(self, deep: bool = False) -> int
 |      Memory usage of my values
 |
 |      Parameters
 |      ----------
 |      deep : bool
 |          Introspect the data deeply, interrogate
 |          `object` dtypes for system-level memory consumption
 |
 |      Returns
 |      -------
 |      bytes used
 |
 |      Notes
 |      -----
 |      Memory usage does not include memory consumed by elements that
 |      are not components of the array if deep=False
 |
 |      See Also
 |      --------
 |      numpy.ndarray.nbytes
 |
 |  min(self, axis=None, skipna=True, *args, **kwargs)
 |      The minimum value of the RangeIndex
 |
 |  tolist(self)
 |      Return a list of the values.
 |
 |      These are each a scalar type, which is a Python scalar
 |      (for str, int, float) or a pandas scalar
 |      (for Timestamp/Timedelta/Interval/Period)
 |
 |      Returns
 |      -------
 |      list
 |
 |      See Also
 |      --------
 |      numpy.ndarray.tolist
 |
 |  ----------------------------------------------------------------------
 |  Class methods defined here:
 |
 |  from_range(data, name=None, dtype=None) from builtins.type
 |      Create RangeIndex from a range object.
 |
 |      Returns
 |      -------
 |      RangeIndex
 |
 |  ----------------------------------------------------------------------
 |  Static methods defined here:
 |
 |  __new__(cls, start=None, stop=None, step=None, dtype=None, copy=False, name=None)
 |      Create and return a new object.  See help(type) for accurate signature.
 |
 |  ----------------------------------------------------------------------
 |  Data descriptors defined here:
 |
 |  dtype
 |      Return the dtype object of the underlying data.
 |
 |  has_duplicates
 |
 |  is_monotonic_decreasing
 |
 |  is_monotonic_increasing
 |
 |  is_unique
 |      return if the index has unique values
 |
 |  nbytes
 |      Return the number of bytes in the underlying data.
 |
 |  size
 |      Return the number of elements in the underlying data.
 |
 |  start
 |      The value of the `start` parameter (``0`` if this was not supplied).
 |
 |  step
 |      The value of the `step` parameter (``1`` if this was not supplied).
 |
 |  stop
 |      The value of the `stop` parameter.
 |
 |  ----------------------------------------------------------------------
 |  Data and other attributes defined here:
 |
 |  __annotations__ = {'_cached_data': typing.Union[numpy.ndarray, NoneTyp...
 |
 |  ----------------------------------------------------------------------
 |  Methods inherited from pandas.core.indexes.numeric.Int64Index:
 |
 |  __divmod__(self, other)
 |
 |  __mod__(self, other)
 |
 |  __pow__(self, other)
 |
 |  __rfloordiv__(self, other)
 |
 |  __rpow__(self, other)
 |
 |  ----------------------------------------------------------------------
 |  Data descriptors inherited from pandas.core.indexes.numeric.Int64Index:
 |
 |  asi8
 |      Integer representation of the values.
 |
 |      Returns
 |      -------
 |      ndarray
 |          An ndarray with int64 dtype.
 |
 |  inferred_type
 |      Always 'integer' for ``Int64Index``
 |
 |  ----------------------------------------------------------------------
 |  Methods inherited from pandas.core.indexes.numeric.NumericIndex:
 |
 |  insert(self, loc, item)
 |      Make new Index inserting new item at location.
 |
 |      Follows Python list.append semantics for negative values.
 |
 |      Parameters
 |      ----------
 |      loc : int
 |      item : object
 |
 |      Returns
 |      -------
 |      new_index : Index
 |
 |  ----------------------------------------------------------------------
 |  Data descriptors inherited from pandas.core.indexes.numeric.NumericIndex:
 |
 |  is_all_dates
 |      Checks that all the labels are datetime objects.
 |
 |  ----------------------------------------------------------------------
 |  Methods inherited from pandas.core.indexes.base.Index:
 |
 |  __and__(self, other)
 |
 |  __array__(self, dtype=None) -> numpy.ndarray
 |      The array interface, return my values.
 |
 |  __array_wrap__(self, result, context=None)
 |      Gets called after a ufunc.
 |
 |  __bool__ = __nonzero__(self)
 |
 |  __copy__(self, **kwargs)
 |
 |  __deepcopy__(self, memo=None)
 |      Parameters
 |      ----------
 |      memo, default None
 |          Standard signature. Unused
 |
 |  __eq__(self, other)
 |      Return self==value.
 |
 |  __ge__(self, other)
 |      Return self>=value.
 |
 |  __gt__(self, other)
 |      Return self>value.
 |
 |  __hash__(self)
 |      Return hash(self).
 |
 |  __iadd__(self, other)
 |
 |  __le__(self, other)
 |      Return self<=value.
 |
 |  __lt__(self, other)
 |      Return self<value.
 |
 |  __ne__(self, other)
 |      Return self!=value.
 |
 |  __nonzero__(self)
 |
 |  __or__(self, other)
 |
 |  __repr__(self)
 |      Return a string representation for this object.
 |
 |  __setitem__(self, key, value)
 |
 |  __xor__(self, other)
 |
 |  append(self, other)
 |      Append a collection of Index options together.
 |
 |      Parameters
 |      ----------
 |      other : Index or list/tuple of indices
 |
 |      Returns
 |      -------
 |      appended : Index
 |
 |  asof(self, label)
 |      Return the label from the index, or, if not present, the previous one.
 |
 |      Assuming that the index is sorted, return the passed index label if it
 |      is in the index, or return the previous index label if the passed one
 |      is not in the index.
 |
 |      Parameters
 |      ----------
 |      label : object
 |          The label up to which the method returns the latest index label.
 |
 |      Returns
 |      -------
 |      object
 |          The passed label if it is in the index. The previous label if the
 |          passed label is not in the sorted index or `NaN` if there is no
 |          such label.
 |
 |      See Also
 |      --------
 |      Series.asof : Return the latest value in a Series up to the
 |          passed index.
 |      merge_asof : Perform an asof merge (similar to left join but it
 |          matches on nearest key rather than equal key).
 |      Index.get_loc : An `asof` is a thin wrapper around `get_loc`
 |          with method='pad'.
 |
 |      Examples
 |      --------
 |      `Index.asof` returns the latest index label up to the passed label.
 |
 |      >>> idx = pd.Index(['2013-12-31', '2014-01-02', '2014-01-03'])
 |      >>> idx.asof('2014-01-01')
 |      '2013-12-31'
 |
 |      If the label is in the index, the method returns the passed label.
 |
 |      >>> idx.asof('2014-01-02')
 |      '2014-01-02'
 |
 |      If all of the labels in the index are later than the passed label,
 |      NaN is returned.
 |
 |      >>> idx.asof('1999-01-02')
 |      nan
 |
 |      If the index is not sorted, an error is raised.
 |
 |      >>> idx_not_sorted = pd.Index(['2013-12-31', '2015-01-02',
 |      ...                            '2014-01-03'])
 |      >>> idx_not_sorted.asof('2013-12-31')
 |      Traceback (most recent call last):
 |      ValueError: index must be monotonic increasing or decreasing
 |
 |  asof_locs(self, where, mask)
 |      Find the locations (indices) of the labels from the index for
 |      every entry in the `where` argument.
 |
 |      As in the `asof` function, if the label (a particular entry in
 |      `where`) is not in the index, the latest index label up to the
 |      passed label is chosen and its index returned.
 |
 |      If all of the labels in the index are later than a label in `where`,
 |      -1 is returned.
 |
 |      `mask` is used to ignore NA values in the index during calculation.
 |
 |      Parameters
 |      ----------
 |      where : Index
 |          An Index consisting of an array of timestamps.
 |      mask : array-like
 |          Array of booleans denoting where values in the original
 |          data are not NA.
 |
 |      Returns
 |      -------
 |      numpy.ndarray
 |          An array of locations (indices) of the labels from the Index
 |          which correspond to the return values of the `asof` function
 |          for every element in `where`.
 |
 |  astype(self, dtype, copy=True)
 |      Create an Index with values cast to dtypes. The class of a new Index
 |      is determined by dtype. When conversion is impossible, a ValueError
 |      exception is raised.
 |
 |      Parameters
 |      ----------
 |      dtype : numpy dtype or pandas type
 |          Note that any signed integer `dtype` is treated as ``'int64'``,
 |          and any unsigned integer `dtype` is treated as ``'uint64'``,
 |          regardless of the size.
 |      copy : bool, default True
 |          By default, astype always returns a newly allocated object.
 |          If copy is set to False and internal requirements on dtype are
 |          satisfied, the original data is used to create a new Index
 |          or the original Index is returned.
 |
 |      Returns
 |      -------
 |      Index
 |          Index with values cast to specified dtype.
 |
 |  delete(self, loc)
 |      Make new Index with passed location(-s) deleted.
 |
 |      Returns
 |      -------
 |      new_index : Index
 |
 |  difference(self, other, sort=None)
 |      Return a new Index with elements from the index that are not in
 |      `other`.
 |
 |      This is the set difference of two Index objects.
 |
 |      Parameters
 |      ----------
 |      other : Index or array-like
 |      sort : False or None, default None
 |          Whether to sort the resulting index. By default, the
 |          values are attempted to be sorted, but any TypeError from
 |          incomparable elements is caught by pandas.
 |

In [41]:
df.values

array([['AK', 339, 1.0, ..., '2020-04-24T19:00:00Z',
        '2020-04-24T20:02:00Z',
        '829ac690ed4c16079a6f1890fcf8105935a055ff'],
       ['AL', 5832, 1.0, ..., '2020-04-24T04:00:00Z',
        '2020-04-24T20:05:00Z',
        '45ada0943397a4f5bd08772ab110f0594bbc7e02'],
       ['AR', 2741, 1.0, ..., '2020-04-24T14:47:00Z',
        '2020-04-24T19:42:00Z',
        'e70e363b75b64ad74efd0b6d046672c6e818750b'],
       ...,
       ['GU', 141, nan, ..., '2020-04-24T11:40:00Z',
        '2020-04-24T20:39:00Z',
        'a555664c8cdbd288357e2a0032b7d9abc3e590af'],
       ['MP', 14, nan, ..., '2020-04-24T04:00:00Z',
        '2020-04-24T20:08:00Z',
        '9d3d9c5668a4eb1441354652adaeba3b5c8b2f78'],
       ['VI', 54, nan, ..., '2020-04-23T04:00:00Z',
        '2020-04-24T18:17:00Z',
        '565ad2d572fd5dc0979ac65a70259e1ba7ad9b4f']], dtype=object)

In [51]:
df_num = df.to_numpy()

In [58]:
df_num.view

In [61]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56 entries, 0 to 55
Data columns (total 30 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   state                   56 non-null     object
 1   positive                56 non-null     int64
 2   positiveScore           52 non-null     float64
 3   negativeScore           52 non-null     float64
 4   negativeRegularScore    52 non-null     float64
 5   commercialScore         52 non-null     float64
 6   grade                   52 non-null     object
 7   score                   52 non-null     float64
 8   notes                   56 non-null     object
 9   dataQualityGrade        56 non-null     object
 10  negative                56 non-null     int64
 11  pending                 7 non-null      float64
 12  hospitalizedCurrently   39 non-null     float64
 13  hospitalizedCumulative  31 non-null     float64
 14  inIcuCurrently          22 non-null     float64
 15  inIcuCumulative         6 non-null      float64
 16  onVentilatorCurrently   16 non-null     float64
 17  onVentilatorCumulative  2 non-null      float64
 18  recovered               33 non-null     float64
 19  lastUpdateEt            56 non-null     object
 20  checkTimeEt             56 non-null     object
 21  death                   55 non-null     float64
 22  hospitalized            31 non-null     float64
 23  total                   56 non-null     int64
 24  totalTestResults        56 non-null     int64
 25  posNeg                  56 non-null     int64
 26  fips                    56 non-null     object
 27  dateModified            56 non-null     object
 28  dateChecked             56 non-null     object
 29  hash                    56 non-null     object
dtypes: float64(15), int64(5), object(10)
memory usage: 13.2+ KB

In [62]:
df.columns

Index(['state', 'positive', 'positiveScore', 'negativeScore',
       'negativeRegularScore', 'commercialScore', 'grade', 'score', 'notes',
       'dataQualityGrade', 'negative', 'pending', 'hospitalizedCurrently',
       'hospitalizedCumulative', 'inIcuCurrently', 'inIcuCumulative',
       'onVentilatorCurrently', 'onVentilatorCumulative', 'recovered',
       'lastUpdateEt', 'checkTimeEt', 'death', 'hospitalized', 'total',
       'totalTestResults', 'posNeg', 'fips', 'dateModified', 'dateChecked',
       'hash'],
      dtype='object')

In [65]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56 entries, 0 to 55
Data columns (total 30 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   state                   56 non-null     object
 1   positive                56 non-null     int64
 2   positiveScore           52 non-null     float64
 3   negativeScore           52 non-null     float64
 4   negativeRegularScore    52 non-null     float64
 5   commercialScore         52 non-null     float64
 6   grade                   52 non-null     object
 7   score                   52 non-null     float64
 8   notes                   56 non-null     object
 9   dataQualityGrade        56 non-null     object
 10  negative                56 non-null     int64
 11  pending                 7 non-null      float64
 12  hospitalizedCurrently   39 non-null     float64
 13  hospitalizedCumulative  31 non-null     float64
 14  inIcuCurrently          22 non-null     float64
 15  inIcuCumulative         6 non-null      float64
 16  onVentilatorCurrently   16 non-null     float64
 17  onVentilatorCumulative  2 non-null      float64
 18  recovered               33 non-null     float64
 19  lastUpdateEt            56 non-null     object
 20  checkTimeEt             56 non-null     object
 21  death                   55 non-null     float64
 22  hospitalized            31 non-null     float64
 23  total                   56 non-null     int64
 24  totalTestResults        56 non-null     int64
 25  posNeg                  56 non-null     int64
 26  fips                    56 non-null     object
 27  dateModified            56 non-null     object
 28  dateChecked             56 non-null     object
 29  hash                    56 non-null     object
dtypes: float64(15), int64(5), object(10)
memory usage: 13.2+ KB

In [70]:
df.loc[0:50,['state','positiveScore']]

   state  positiveScore
0     AK            1.0
1     AL            1.0
2     AR            1.0
3     AZ            1.0
4     CA            1.0
5     CO            1.0
6     CT            1.0
7     DC            1.0
8     DE            1.0
9     FL            1.0
10    GA            1.0
11    HI            1.0
12    IA            1.0
13    ID            1.0
14    IL            1.0
15    IN            1.0
16    KS            1.0
17    KY            1.0
18    LA            1.0
19    MA            1.0
20    MD            1.0
21    ME            1.0
22    MI            1.0
23    MN            1.0
24    MO            1.0
25    MS            1.0
26    MT            1.0
27    NC            1.0
28    ND            1.0
29    NE            1.0
30    NH            1.0
31    NJ            1.0
32    NM            1.0
33    NV            1.0
34    NY            1.0
35    OH            1.0
36    OK            1.0
37    OR            1.0
38    PA            1.0
39    RI            1.0
40    SC            1.0
41    SD            1.0
42    TN            1.0
43    TX            1.0
44    UT            1.0
45    VA            1.0
46    VT            1.0
47    WA            0.0
48    WI            1.0
49    WV            1.0
50    WY            1.0

In [71]:
df.iloc[0:2,0:2]

  state  positive
0    AK       339
1    AL      5832

In [72]:
df.loc[0:2,['state','positiveScore']]

  state  positiveScore
0    AK            1.0
1    AL            1.0
2    AR            1.0

In [76]:
df.state.index.size

56

In [78]:
df['positiveScore'].apply(type).unique()

array([<class 'float'>], dtype=object)

In [81]:
import pandas as pd

In [83]:
set(dir(pd.Series))

{'T',
 '_AXIS_ALIASES',
 '_AXIS_IALIASES',
 '_AXIS_LEN',
 '_AXIS_NAMES',
 '_AXIS_NUMBERS',
 '_AXIS_ORDERS',
 '_AXIS_REVERSED',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__div__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__long__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdiv__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '__xor__',
 '_accessors',
 '_add_numeric_operations',
 '_add_series_or_dataframe_operations',
 '_agg_by_level',
 '_agg_examples_doc',
 '_agg_see_also_doc',
 '_aggregate',
 '_aggregate_multiple_funcs',
 '_align_frame',
 '_align_series',
 '_binop',
 '_box_item_values',
 '_builtin_table',
 '_can_hold_na',
 '_check_inplace_setting',
 '_check_is_chained_assignment_possible',
 '_check_label_or_level_ambiguity',
 '_check_setitem_copy',
 '_clear_item_cache',
 '_clip_with_one_bound',
 '_clip_with_scalar',
 '_consolidate',
 '_consolidate_inplace',
 '_construct_axes_dict',
 '_construct_axes_dict_from',
 '_construct_axes_from_arguments',
 '_constructor',
 '_constructor_expanddim',
 '_constructor_sliced',
 '_convert',
 '_convert_dtypes',
 '_create_indexer',
 '_cython_table',
 '_deprecations',
 '_dir_additions',
 '_dir_deletions',
 '_drop_axis',
 '_drop_labels_or_levels',
 '_find_valid_index',
 '_from_axes',
 '_get_axis',
 '_get_axis_name',
 '_get_axis_number',
 '_get_axis_resolvers',
 '_get_block_manager_axis',
 '_get_bool_data',
 '_get_cacher',
 '_get_cleaned_column_resolvers',
 '_get_cython_func',
 '_get_index_resolvers',
 '_get_item_cache',
 '_get_label_or_level_values',
 '_get_numeric_data',
 '_get_value',
 '_get_values',
 '_get_values_tuple',
 '_get_with',
 '_gotitem',
 '_iget_item_cache',
 '_index',
 '_indexed_same',
 '_info_axis',
 '_info_axis_name',
 '_info_axis_number',
 '_init_dict',
 '_init_mgr',
 '_internal_get_values',
 '_internal_names',
 '_internal_names_set',
 '_is_builtin_func',
 '_is_cached',
 '_is_copy',
 '_is_datelike_mixed_type',
 '_is_label_or_level_reference',
 '_is_label_reference',
 '_is_level_reference',
 '_is_mixed_type',
 '_is_numeric_mixed_type',
 '_is_view',
 '_ix',
 '_ixs',
 '_map_values',
 '_maybe_cache_changed',
 '_maybe_update_cacher',
 '_metadata',
 '_ndarray_values',
 '_needs_reindex_multi',
 '_obj_with_exclusions',
 '_protect_consolidate',
 '_reduce',
 '_reindex_axes',
 '_reindex_indexer',
 '_reindex_multi',
 '_reindex_with_indexers',
 '_repr_data_resource_',
 '_repr_latex_',
 '_reset_cache',
 '_reset_cacher',
 '_selected_obj',
 '_selection',
 '_selection_list',
 '_selection_name',
 '_set_as_cached',
 '_set_axis',
 '_set_axis_name',
 '_set_is_copy',
 '_set_item',
 '_set_labels',
 '_set_name',
 '_set_subtyp',
 '_set_value',
 '_set_values',
 '_set_with',
 '_set_with_engine',
 '_setup_axes',
 '_slice',
 '_stat_axis',
 '_stat_axis_name',
 '_stat_axis_number',
 '_take_with_is_copy',
 '_to_dict_of_blocks',
 '_try_aggregate_string_function',
 '_typ',
 '_unpickle_series_compat',
 '_update_inplace',
 '_validate_dtype',
 '_values',
 '_where',
 '_xs',
 'abs',
 'add',
 'add_prefix',
 'add_suffix',
 'agg',
 'aggregate',
 'align',
 'all',
 'any',
 'append',
 'apply',
 'argmax',
 'argmin',
 'argsort',
 'array',
 'asfreq',
 'asof',
 'astype',
 'at',
 'at_time',
 'attrs',
 'autocorr',
 'axes',
 'between',
 'between_time',
 'bfill',
 'bool',
 'cat',
 'clip',
 'combine',
 'combine_first',
 'convert_dtypes',
 'copy',
 'corr',
 'count',
 'cov',
 'cummax',
 'cummin',
 'cumprod',
 'cumsum',
 'describe',
 'diff',
 'div',
 'divide',
 'divmod',
 'dot',
 'drop',
 'drop_duplicates',
 'droplevel',
 'dropna',
 'dt',
 'dtype',
 'dtypes',
 'duplicated',
 'empty',
 'eq',
 'equals',
 'ewm',
 'expanding',
 'explode',
 'factorize',
 'ffill',
 'fillna',
 'filter',
 'first',
 'first_valid_index',
 'floordiv',
 'ge',
 'get',
 'groupby',
 'gt',
 'hasnans',
 'head',
 'hist',
 'iat',
 'idxmax',
 'idxmin',
 'iloc',
 'index',
 'infer_objects',
 'interpolate',
 'is_monotonic',
 'is_monotonic_decreasing',
 'is_monotonic_increasing',
 'is_unique',
 'isin',
 'isna',
 'isnull',
 'item',
 'items',
 'iteritems',
 'keys',
 'kurt',
 'kurtosis',
 'last',
 'last_valid_index',
 'le',
 'loc',
 'lt',
 'mad',
 'map',
 'mask',
 'max',
 'mean',
 'median',
 'memory_usage',
 'min',
 'mod',
 'mode',
 'mul',
 'multiply',
 'name',
 'nbytes',
 'ndim',
 'ne',
 'nlargest',
 'notna',
 'notnull',
 'nsmallest',
 'nunique',
 'pct_change',
 'pipe',
 'plot',
 'pop',
 'pow',
 'prod',
 'product',
 'quantile',
 'radd',
 'rank',
 'ravel',
 'rdiv',
 'rdivmod',
 'reindex',
 'reindex_like',
 'rename',
 'rename_axis',
 'reorder_levels',
 'repeat',
 'replace',
 'resample',
 'reset_index',
 'rfloordiv',
 'rmod',
 'rmul',
 'rolling',
 'round',
 'rpow',
 'rsub',
 'rtruediv',
 'sample',
 'searchsorted',
 'sem',
 'set_axis',
 'shape',
 'shift',
 'size',
 'skew',
 'slice_shift',
 'sort_index',
 'sort_values',
 'sparse',
 'squeeze',
 'std',
 'str',
 'sub',
 'subtract',
 'sum',
 'swapaxes',
 'swaplevel',
 'tail',
 'take',
 'to_clipboard',
 'to_csv',
 'to_dict',
 'to_excel',
 'to_frame',
 'to_hdf',
 'to_json',
 'to_latex',
 'to_list',
 'to_markdown',
 'to_numpy',
 'to_period',
 'to_pickle',
 'to_sql',
 'to_string',
 'to_timestamp',
 'to_xarray',
 'tolist',
 'transform',
 'transpose',
 'truediv',
 'truncate',
 'tshift',
 'tz_convert',
 'tz_localize',
 'unique',
 'unstack',
 'update',
 'value_counts',
 'values',
 'var',
 'view',
 'where',
 'xs'}

In [87]:
datemodified = df.dateModified

In [88]:
datemodified.describe()

count                       56
unique                      30
top       2020-04-24T04:00:00Z
freq                        10
Name: dateModified, dtype: object

In [100]:
column_dir = {x : x.upper() for x  in df.columns}

In [102]:
df.rename(columns=column_dir).head()

,STATE,POSITIVE,POSITIVESCORE,NEGATIVESCORE,NEGATIVEREGULARSCORE,COMMERCIALSCORE,GRADE,SCORE,NOTES,DATAQUALITYGRADE,...,CHECKTIMEET,DEATH,HOSPITALIZED,TOTAL,TOTALTESTRESULTS,POSNEG,FIPS,DATEMODIFIED,DATECHECKED,HASH
0,AK,339,1.0,1.0,1.0,1.0,A,4.0,"Please stop using the ""total"" field. Use ""tota...",B,...,4/24 16:02,9.0,NaN,12281,12281,12281,02,2020-04-24T19:00:00Z,2020-04-24T20:02:00Z,829ac690ed4c16079a6f1890fcf8105935a055ff
1,AL,5832,1.0,1.0,0.0,1.0,B,3.0,"Please stop using the ""total"" field. Use ""tota...",B,...,4/24 16:05,197.0,768.0,52695,52695,52695,01,2020-04-24T04:00:00Z,2020-04-24T20:05:00Z,45ada0943397a4f5bd08772ab110f0594bbc7e02
2,AR,2741,1.0,1.0,1.0,1.0,A,4.0,"Please stop using the ""total"" field. Use ""tota...",B,...,4/24 15:42,45.0,291.0,35578,35578,35578,05,2020-04-24T14:47:00Z,2020-04-24T19:42:00Z,e70e363b75b64ad74efd0b6d046672c6e818750b
3,AZ,6045,1.0,1.0,0.0,1.0,B,3.0,"Please stop using the ""total"" field. Use ""tota...",A+,...,4/24 15:39,266.0,984.0,60714,60714,60714,04,2020-04-24T04:00:00Z,2020-04-24T19:39:00Z,72d72c4092636c2a96a366a5895055feccc0aeef
4,CA,39254,1.0,1.0,0.0,1.0,B,3.0,"Please stop using the ""total"" field. Use ""tota...",B,...,4/24 17:00,1562.0,NaN,494173,494173,494173,06,2020-04-23T04:00:00Z,2020-04-24T21:00:00Z,0711cfd3633ed6d50a0d5f33573f8929f3dfaed2

list